#ifndef SERVERMESSAGETYPEENUM_H
#define SERVERMESSAGETYPEENUM_H

namespace Engine {

enum class ServerMessageType {
    UNKNOWN,
    WORLD_BASIC,
    OWN_CHARACTER,
    OWN_EQUIPMENT,
    OWN_INVENTORY,
    CHARACTER,
    CREATURE,
    CHARACTER_EVENT_ATTACK,
    CHARACTER_EVENT_LEAVE,
    CREATURE_EVENT_LEAVE,
};

} // namespace Engine

#endif // SERVERMESSAGETYPEENUM_H
