#ifndef WORLDEVENTTYPE_H
#define WORLDEVENTTYPE_H

namespace Server {

enum class WorldEventType {
    CHARACTER_ENTERED,
    CHARACTER_MOVED,
    CHARACTER_LEFT,
    CHARACTER_VITALS_CHANGED,
    CHARACTER_ATTACK_STARTED,
    CHARACTER_ATTACKED,
    CREATURE_MOVED,
    CREATURE_VITALS_CHANGED,
    CREATURE_LEFT,
    CREATURE_ATTACK_STARTED,
    CREATURE_ATTACKED,
};

} // namespace Server

#endif // WORLDEVENTTYPE_H
